# netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
from = "/contact"
to = "/contact.html"
status = 200

[[redirects]]
from = "/thank-you"
to = "/thank-you.html"
status = 200